import type { Metadata } from "next";
import { Host_Grotesk } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/provider/theme-provider";

const font = Host_Grotesk({
  subsets:["latin","latin-ext"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
    suppressHydrationWarning
    >
      <body
      suppressHydrationWarning
        className={`${font.className}  antialiased`}
      >
      <ThemeProvider
      attribute={'class'}
      disableTransitionOnChange
      enableSystem
      defaultTheme="dark"
      >
          {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
